//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceDataAccess
{
    using System;
    using System.Collections.Generic;

    public partial class Company
    {
        public int Id { get; set; }
        public string Symbol { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> LastSale { get; set; }
        public Nullable<decimal> MarketCapital { get; set; }
        public string ADRTSO { get; set; }
        private Nullable<short> IpoYear;
        public Nullable<short> IPOYear { get { return this.IpoYear??0; }  set { this.IpoYear = value; }  }
        public string Sector { get; set; }
        public string Industry { get; set; }
        public string QuoteSite { get; set; }
        public string Exchange { get; set; }
    }
}
