//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeStatement
    {
        public int CompanyId { get; set; }
        public int StatementId { get; set; }
        public System.DateTime StatementDate { get; set; }
        public Nullable<decimal> TotalRevenue { get; set; }
        public Nullable<decimal> CostofRevenue { get; set; }
        public Nullable<decimal> GrossProfit { get; set; }
        public Nullable<decimal> OperatingExpenses { get; set; }
        public Nullable<decimal> SalesGenAdmin { get; set; }
        public Nullable<decimal> NonRecurringItems { get; set; }
        public Nullable<decimal> OtherOperatingItems { get; set; }
        public Nullable<decimal> OperatingIncome { get; set; }
        public Nullable<decimal> AddlIncExpitems { get; set; }
        public Nullable<decimal> EarningsBefIntTax { get; set; }
        public Nullable<decimal> InterestExpense { get; set; }
        public Nullable<decimal> EarningsBeforeTax { get; set; }
        public Nullable<decimal> IncomeTax { get; set; }
        public Nullable<decimal> MinorityInterest { get; set; }
        public Nullable<decimal> EquityEarnLossUnconSubs { get; set; }
        public Nullable<decimal> NetIncomeContOperations { get; set; }
        public Nullable<decimal> NetIncome { get; set; }
        public Nullable<decimal> NetIncApptoComShareholders { get; set; }
    }
}
